### PR TITLE
Add a podspec.

### PR DESCRIPTION
**Pull request by streeter**

### CODE REVIEW

**Comment by streeter** [comment]
For reference, I got this podspec added to the Cocoapods specs repo with CocoaPods/Specs#4721.

**Comment by seanm** [comment]
OK, seems harmless to merge this.  Will you sync the changes with the Cocoapods specs repo please?

**Comment by streeter** [comment]
Yep, will do. Wanted to make sure it was synced up with the podspec here first.

**Comment by streeter** [comment]
The changes are now merged into the upstream repo.

**Pull request merged**
